syntax = "proto3";

package clustering.v1;

option go_package = "github.com/hedisam/goactor/gen/protos/clustering/v1;clusteringv1";

message UserMessage {
  bytes data = 1;
}

message InternalMessage {
  bytes data = 1;
}

message SystemMessage {
  string sender_ref = 1;
  string sender_node = 2;
  oneof request {
    Link link = 100;
    Unlink unlink = 101;
    Monitor monitor = 102;
    Demonitor demonitor = 103;
  }
}

message Link {}

message Unlink {}

message Monitor {}

message Demonitor {}